services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Beux\Pagemodule\ModifyPageEditButtons:
    tags:
      - name: event.listener
        identifier: 'modifyPageEditButtonsListener'
